#spring.application.name=config-sevice
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
        uri:
        search-paths: config-service