#spring.application.name=config-sevice
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/NandoAgueroS/tutorial-microservicios
          search-paths: config-data